### ISSUE TITLE
English Translation?

### ISSUE THREAD

**Issue by iodevadmin** [ant-design/ant-ux#10]
Is there a zip file for an english translation for Ant UX? I very much like the design and would like to experiment, but cannot understand the Chinese characterizations.

I appreciate any help. Thanks!

**Comment by beynar** [comment]
+1 👍

**Comment by gerlv** [comment]
@inventryapp @nonomoute Google translate + 10 minutes of free time, but the result is good.

great work @hi-caicai this is definitely something I will use. 

If you want, I can automate translation for Sketch file. In a nutshell, a sketch file is a zip file with some metadata + JSON which stores the data (http://sketchplugins.com/d/87-new-file-format-in-sketch-43). 

I can create a small script which you can run locally and it will create an English translation. The only thing you will need to do when you change something is a CSV file with Chinese and English labels.

Let me know if you are interested. My email is oleg [at] ger.lv 
It looks like a great project I will be happy to help.

[Ant UX-Sketch Eng.zip](https://github.com/ant-design/ant-ux/files/1519137/Ant.UX-Sketch.Eng.zip)

Btw, the website doesn't have a link to a Sketch file.

**Comment by hi-caicai** [comment]
Thanks @gerlv ，I will replace the document which you translated .

**Comment by hi-caicai** [comment]
done
