### ISSUE TITLE
Illustrator and XD files

### ISSUE THREAD

**Issue by AkdM** [ant-design/ant-ux#11]
Is there any roadmap about the Illustrator and Adobe XD files?

Thanks.

**Comment by hi-caicai** [comment]
OK，I will provide the Adobe XD files in a few weeks

**Comment by AkdM** [comment]
Wonderful. Thanks !

**Comment by hi-caicai** [comment]
It has been provided. You can download it on the website  http://ux.ant.design/

**Comment by trieudh58** [comment]
Hey @hi-caicai . I found the Adobe XD designs too generic. It does not contain some components like buttons, tables,... Or am I missing something?

**Comment by hi-caicai** [comment]
Can you show me the screenshots ？ @trieudh58

**Comment by trieudh58** [comment]
Here are my two screenshots:
- https://prnt.sc/krk926
- https://prnt.sc/krk94s

I downloaded the XD file from http://ux.ant.design/

**Comment by hi-caicai** [comment]
ok, some components are missing and I will add them later @trieudh58

**Comment by krokofant** [comment]
@hi-caicai  Any progress on this?

**Comment by isaiahols** [comment]
So are we never getting updated xd files?

**Comment by krokofant** [comment]
@isaiahols Might as well create a new issue
