### ISSUE TITLE
为什么建议尽可能不使用面包屑，求解答

### ISSUE THREAD

**Issue by cdxzui** [ant-design/ant-ux#14]
![1513302572238](https://user-images.githubusercontent.com/20896513/34022968-56f1f312-e17d-11e7-94b5-e5476ac3352f.jpg)

**Comment by RenderCoder** [comment]
看到腾讯 CDC 面包屑设计的文章里有句话：

> 面包屑不能替代有效的主导航，它是一个辅助功能；一个允许用户定位他们在哪里的辅助导航方案。

[面包屑设计](http://cdc.tencent.com/2009/07/06/面包屑设计/)

**Comment by hi-caicai** [comment]
这个问题在于，如果你本身的框架设计的很合理，用户不需要进去很深的页面，就不需要用。如果你真的需要用面包屑来辅助你的层级跳转的时候，那就用呗。

**Comment by cdxzui** [comment]
谢谢楼上两位🙏
