### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jdittrich** [ant-design/ant-ux#19]
**Problem:** I am unsure under which license the template is. Given that non is specified I assume this is under "normal" copyright, not permitting changes and redistribution. I assume this would limit the use of the templates a bit, particularly if I build a sitemap I want to show publicly.

If the "normal copyright" is intended, it could help if you add this. If you instead intend the templates to be build upon redistributed etc., please add a license, e.g. one of the [creative common](https://creativecommons.org/choose/) ones.

**Comment by hi-caicai** [comment]
Under the MIT license.

**Comment by jdittrich** [comment]
Thanks! could you post that possibly in a license.md in the repo (next to readme.md) or add a License section to the readme itself? I assume this is a question that some people might have, particularly if they want to build more longer-term projects on your awesome templates – in this case, it can be very helpful to show one’s boss that it is all fine and not in danger of getting sued :)

**Comment by hi-caicai** [comment]
done
