### ISSUE TITLE
官网图标拼写错误

### ISSUE THREAD

**Issue by Web3TomCat** [ant-design/ant-ux#28]
不应该是Twitter么？
![1](https://user-images.githubusercontent.com/17536588/124241701-92b1f400-db4e-11eb-81a6-2ba0b308252d.png)

**Comment by afc163** [comment]
没写错。

<img width="610" alt="图片" src="https://user-images.githubusercontent.com/507615/124265560-6c00b700-db68-11eb-8cbf-2a5cc5eed610.png">
