### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by SNaushadS** [ant-design/ant-ux#7]
hello there,

Is there an English version available for the Axure Libraries ? 

Thanks,
Naushad.

**Comment by hi-caicai** [comment]
The axure version already supports English
![screen shot 2017-08-04 at 17 50 15](https://user-images.githubusercontent.com/1811819/28963913-64eb9a2a-793d-11e7-8f9a-ca2a7488e3cf.png)

**Comment by SNaushadS** [comment]
Thanks. I got it post download
