### ISSUE TITLE
ant-design有计划提供adobe xd版么？

### ISSUE THREAD

**Issue by jinnchen** [ant-design/ant-ux#9]
最近正在使用 adobe xd，可是该项目还没有adobe版。虽然该软件还在beta阶段，功能比axure少多了（方向也不同，比较其实不合适），还有挺多头疼的地方，还是觉得比axure更加好用。
相信只要adobe用心去改进这款软件，是很有希望大火的。
希 望ant-design 在 adobe xd 正式版发布，且风评不错时能考虑推出adobe xd版。

**Comment by QuadDepo** [comment]
+1

**Comment by hi-caicai** [comment]
这个模版，我会在几周会提供 Adobe XD 版本

**Comment by hi-caicai** [comment]
Ant UX 已经提供 Adobe XD 版本，可以在官网下载

**Comment by MicoleChan** [comment]
有没有计划什么时候发布一个类似Axure和Sketch版本的AdobeXD样例模板？

**Comment by QuadDepo** [comment]
@MicoleChan I will take a look soon
